"use client";

import * as React from "react";
import { api } from "@/lib/api";
import { Incident } from "@/types";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { FileText, Download, CheckCircle2, AlertCircle, RefreshCw, ArrowRight } from "lucide-react";
import Link from "next/link";

export default function ReportsPage() {
  const [incidents, setIncidents] = React.useState<Incident[]>([]);
  const [isLoading, setIsLoading] = React.useState(true);

  const fetchReports = React.useCallback(async () => {
    setIsLoading(true);
    try {
      const data = await api.getIncidents();
      setIncidents(data || []);
    } catch (err) {
      console.error("Failed to load reports/incidents:", err);
    } finally {
      setIsLoading(false);
    }
  }, []);

  React.useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const handleExportPostMortem = (inc: Incident) => {
    const reportText = `=====================================================
OPSFORGE AUTONOMOUS SRE INCIDENT POST-MORTEM REPORT
=====================================================
Report ID:      PM-${inc.id.replace("INC-", "")}
Incident ID:    ${inc.id}
Title:          ${inc.title}
Service:        ${inc.service}
Severity:       ${inc.severity}
Status:         ${inc.status}
Created At:     ${inc.created_at || "N/A"}
Alert Source:   ${inc.alert_source || "Telemetry Alerting"}

SUMMARY & DESCRIPTION:
${inc.description || "System telemetry alert triggered subagent investigation."}

IMPACT:
${inc.estimated_impact || (inc.affected_users ? `Affected users: ${inc.affected_users}` : "Service performance degradation detected.")}

ROOT CAUSE ANALYSIS:
${
  typeof inc.root_cause === "object" && inc.root_cause
    ? (inc.root_cause.hypothesis || JSON.stringify(inc.root_cause, null, 2))
    : (inc.root_cause || "Diagnostic analysis completed by autonomous subagent swarm.")
}

PROPOSED / EXECUTED ACTION:
${
  typeof inc.proposed_action === "object" && inc.proposed_action
    ? (inc.proposed_action.description || JSON.stringify(inc.proposed_action, null, 2))
    : (inc.proposed_action || "Remediation applied and verified against telemetry baseline.")
}
=====================================================
Generated by OpsForge Autonomous SRE Platform
`;

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `OpsForge_PostMortem_${inc.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-zinc-900 border border-zinc-800">
              <FileText className="h-5 w-5 text-zinc-300" />
            </div>
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-zinc-100">
              Incident Post-Mortems & Reports Archive
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-zinc-400 mt-1">
            Auto-generated SRE root-cause analysis, timeline logs, and permanent preventive actions.
          </p>
        </div>

        <Button
          variant="outline"
          size="sm"
          onClick={fetchReports}
          isLoading={isLoading}
          className="self-start sm:self-auto font-mono text-xs gap-1.5"
        >
          <RefreshCw className="h-3.5 w-3.5" />
          Refresh Reports
        </Button>
      </div>

      {/* Reports List */}
      {incidents.length === 0 ? (
        <Card className="border-zinc-800 bg-zinc-900/40 p-12 text-center">
          <FileText className="h-10 w-10 text-zinc-500 mx-auto mb-3" />
          <h2 className="text-base font-bold text-zinc-200">No Post-Mortem Reports Archived</h2>
          <p className="text-xs text-zinc-400 mt-1 max-w-md mx-auto">
            When incidents are triggered and resolved in OpsForge, complete SRE post-mortem reports and root-cause analysis will appear here dynamically.
          </p>
          <div className="mt-5">
            <Link href="/incidents">
              <Button variant="primary" size="sm" className="font-mono text-xs gap-1.5">
                Go to Incidents Dashboard
                <ArrowRight className="h-3.5 w-3.5" />
              </Button>
            </Link>
          </div>
        </Card>
      ) : (
        <div className="space-y-4">
          {incidents.map((inc) => {
            const reportId = `PM-${inc.id.replace("INC-", "")}`;
            const dateStr = inc.created_at
              ? new Date(inc.created_at).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })
              : "Recent";

            const rootCauseText =
              typeof inc.root_cause === "object" && inc.root_cause
                ? (inc.root_cause.hypothesis || JSON.stringify(inc.root_cause))
                : (inc.root_cause || inc.description || "Subagent telemetry diagnostic in progress.");

            const impactText =
              inc.estimated_impact ||
              (inc.affected_users ? `Affected Users: ${inc.affected_users}` : "System telemetry alert registered.");

            return (
              <Card
                key={inc.id}
                className="border-zinc-800/80 bg-zinc-900/40 hover:border-zinc-700 transition-all shadow-sm"
              >
                <CardHeader className="pb-3 border-zinc-800/60">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-xs font-medium text-zinc-200 px-2.5 py-0.5 rounded bg-zinc-800 border border-zinc-700">
                        {reportId}
                      </span>
                      <span className="font-mono text-xs text-zinc-400 bg-zinc-900 px-2 py-0.5 rounded border border-zinc-800">
                        {inc.id}
                      </span>
                      <span className="text-[10px] font-mono font-medium text-zinc-300 bg-zinc-800/80 px-2 py-0.5 rounded border border-zinc-700">
                        {inc.service}
                      </span>
                    </div>
                    <span className="text-xs font-mono text-zinc-400">{dateStr}</span>
                  </div>
                  <CardTitle className="text-base text-zinc-100 mt-1.5">
                    {inc.title}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 pt-1">
                  <div className="text-xs text-zinc-300">
                    <span className="text-zinc-400 font-mono font-semibold">Impact: </span>
                    {impactText}
                  </div>
                  <div className="text-xs text-zinc-300">
                    <span className="text-zinc-400 font-mono font-semibold">Root Cause: </span>
                    {rootCauseText}
                  </div>
                  <div className="flex items-center justify-between pt-3 border-t border-zinc-800/60">
                    <Link
                      href={`/incidents/${inc.id}`}
                      className="text-xs text-zinc-400 hover:text-zinc-100 font-mono inline-flex items-center gap-1 transition-colors"
                    >
                      View Incident Workspace &rarr;
                    </Link>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleExportPostMortem(inc)}
                      className="font-mono text-xs gap-1.5"
                    >
                      <Download className="h-3.5 w-3.5" />
                      Export Report
                    </Button>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
