"""Pydantic schemas for Incident Report endpoints."""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class ReportRootCause(BaseModel):
    """Root cause section of incident report."""
    description: str
    confidence: float
    evidence: List[str] = []


class ReportApproval(BaseModel):
    """Approval section of incident report."""
    requested_at: Optional[datetime] = None
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None


class ReportRemediation(BaseModel):
    """Remediation section of incident report."""
    action: str
    executed_at: Optional[datetime] = None
    execution_time_seconds: int = 0
    approval: Optional[ReportApproval] = None


class ReportMetrics(BaseModel):
    """Metrics verification section of incident report."""
    before: str
    during: Optional[str] = None
    after: str
    recovery_time_minutes: Optional[int] = None


class ReportVerification(BaseModel):
    """Verification section of incident report."""
    verified_at: Optional[datetime] = None
    metrics: Dict[str, ReportMetrics] = {}
    status: str = "PENDING"


class IncidentReportResponse(BaseModel):
    """Full incident post-mortem report response."""
    incident_id: str
    title: str
    service: str
    severity: str
    status: str
    duration_minutes: Optional[int] = None
    detected_at: datetime
    resolved_at: Optional[datetime] = None
    root_cause: Optional[ReportRootCause] = None
    remediation: Optional[ReportRemediation] = None
    verification: Optional[ReportVerification] = None
    agent_summary: str = "Report generated by OpsForge AI Incident Response Engine."
    timeline_event_count: int = 0
    generated_at: datetime


class ReportExportRequest(BaseModel):
    """Request schema for exporting a report."""
    format: str = Field(default="JSON", description="Export format: PDF, MARKDOWN, JSON, HTML")
